"""empty message

Revision ID: 21afb4485aed
Revises: dd4b1215d1b6
Create Date: 2021-06-08 17:34:13.310639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21afb4485aed'
down_revision = 'dd4b1215d1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id_character', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('homeworld', sa.String(length=35), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id_character')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    # ### end Alembic commands ###
