"""empty message

Revision ID: 6129e6f01c41
Revises: 660a675e400b
Create Date: 2021-06-09 10:20:33.056561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6129e6f01c41'
down_revision = '660a675e400b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id_people', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('homeworld', sa.String(length=35), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id_people')
    )
    op.drop_table('character')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id_character', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=35), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('homeworld', mysql.VARCHAR(length=35), nullable=True),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('species', mysql.VARCHAR(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id_character'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('people')
    # ### end Alembic commands ###
