"""empty message

Revision ID: 660a675e400b
Revises: 21afb4485aed
Create Date: 2021-06-08 18:32:57.376520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660a675e400b'
down_revision = '21afb4485aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id_planet', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=35), nullable=True),
    sa.Column('climate', sa.String(length=10), nullable=True),
    sa.Column('diameter', sa.Integer(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('terrain', sa.String(length=35), nullable=True),
    sa.PrimaryKeyConstraint('id_planet')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
